CC = g++
CFLAGS = -std=c++11 -pthread

task1: task1.cpp
	$(CC) $(CFLAGS) task1.cpp -o out1


task2: task2.cpp
	$(CC) $(CFLAGS) task2.cpp -o out2


task2_cheker: task2_cheker.cpp
	g++ task2_cheker.cpp -o chek